Vagrant.configure("2") do |config|
    config.vm.box = "centos/8"
    config.vm.box_version = "1905.1"

    config.vm.network "public_network", ip: "192.168.0.11"

    config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
    end

    # Forward ports
    config.vm.network "forwarded_port", guest: 8080, host: 8080 # web server
    config.vm.network "forwarded_port", guest: 5432, host: 5432 # Postgres

    config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end

    # If true, then any SSH connections made will enable agent forwarding.
    config.ssh.forward_agent = true

    # Share additional folders to the guest VM.
    config.vm.synced_folder "data", "/data"

    # Bash provision script
    config.vm.provision "shell", path: "provision/setup.sh"

    # Upload user's ssh key into box so it can be used for downloading stuff from stash
    ssh_key_path = "~/.ssh/"
    config.vm.provision "shell", inline: "mkdir -p /home/vagrant/.ssh"
    config.vm.provision "file", source: "#{ ssh_key_path + 'id_rsa' }", destination: "/home/vagrant/.ssh/id_rsa"
    config.vm.provision "file", source: "#{ ssh_key_path + 'id_rsa.pub' }", destination: "/home/vagrant/.ssh/id_rsa.pub"

    config.vm.provision "shell", inline: <<-SHELL
        #
        # Update and install basic linux programs for development
        #
        sudo yum update -y
        sudo yum install -y wget
        sudo yum install -y curl
        sudo yum install -y vim
        sudo yum install -y git
        sudo yum install -y build-essential
        sudo yum install -y unzip
        #
        # Install Ansible
        #
        cd /usr/local/src
        sudo yum -y install git python-jinja2 python-paramiko PyYAML make MySQL-python
        sudo git clone https://github.com/ansible/ansible.git
        cd /usr/local/src/ansible
        sudo git submodule update --init --recursive
        sudo make install
        sudo echo "[localhost]" > ~/ansible_hosts
        sudo echo "localhost ansible_connection=local" >> ~/ansible_hosts
        export ANSIBLE_INVENTORY=~/ansible_hosts
    SHELL

end